### ISSUE TITLE
gcc: error: unrecognized command line option ‘-Wl’; did you mean ‘-W’?

### ISSUE THREAD

**Issue by ghost** [genx-dev/genx#2]
Hellow there,

I'm trying to install the software in Manjaro Linux. I'm using python 3.7.4
The initial error i got was 
`fatal error: numpy/arrayobject.h no such file or directory`
but that was solved crating a symbolic link with `sudo ln -s /usr/lib/python3.7/site-packages/numpy/core/include/numpy /usr/include/numpy`

Afterwards i got 
`building 'genx.models.lib.offspec_ext' extension`
`gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/include/python3.7m -c genx/models/lib/offspec_ext.c -o build/temp.linux-x86_64-3.7/genx/models/lib/offspec_ext.o -Wno-cpp`
`gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.7/genx/models/lib/offspec_ext.o -L/usr/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/genx/models/lib/offspec_ext.cpython-37m-x86_64-linux-gnu.so -Wl`
`gcc: error: unrecognized command line option ‘-Wl’; did you mean ‘-W’?`
`error: command 'gcc' failed with exit status 1`
I tried to search for the `offspec_ext.cpython-37m-x86_64-linux-gnu.so` but there is no such file in that path.

I tried to change the line in `setup.py` from
`        kwargs = {'extra_link_args': ['-Wl'], 'extra_compile_args': ['-Wno-cpp']}` to
`        kwargs = {'extra_link_args': ['-W'], 'extra_compile_args': ['-Wno-cpp']}`
and the installation continued until I got the error 
`running install_data
error: can't copy 'changelog.txt': doesn't exist or not a regular file`

It was right I changed the flag of the gcc compiler or should I try something else? Somewhere I found the should have an option parsed after the flag.
If it was right I changed the flag then, what is the last error I mentioned before?

Thanks in advance

**Comment by kibbi10** [comment]
The linker option '-Wl' should work, works for me on MacOS and Ubuntu 18.04 LTS. What is your version of gcc? Just to clarify, you did run the setup using 
`sudo python setup.py install` or `sudo python setup.py build`?

I saw the last error while compiling, about it not finding files. There are apparently missing files in the root folder, e.g. you need to create the files "changelog.txt" and "README.txt" or edit the setup.py and delete them from the _data_files list in setup.py

**Comment by ghost** [comment]
Thanks for the reply!
I run gcc version 9.2.0 and i run the setup via `sudo python3 setup.py install`.

Nice, thanks I'll modify the script and I'll give it a try once again.

Edit: I changed the flag from `-Wl` to `-W` and removed the "changelog.txt" and "README.txt" from the `_data_files` list and everything went well.
GenX is now installed. I loaded some .hgx projects with no problem, no the only thing it remains is to start a whole new project. 

BTW I have encountered a small bug, when I lunch the software the plot screen covers only half of the space it should cover. I have to resize the window i.e to maximize it in order to appears as it should be. It's not a big deal, I'm just reporting it.
